eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: DATACOLLECTIONS
  datasource:
    password: Password@sql
    url: jdbc:mysql://localhost:3306/insurance
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
