eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9191
spring:
  application:
    name: CREATEAPPLICATION
  datasource:
    password: Password@sql
    url: jdbc:mysql://localhost:3306/insurance
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
